START TRANSACTION;
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (110, '1016037506E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (111, 'Funciones_Asistente_Contable', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (112, '1121936876', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (113, '1014180459', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (114, '43728382E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (115, '1014216060E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (116, '52967140E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (117, '52844528E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (118, '1032414423E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (119, '478731E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (120, '1128452509E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (121, '1010056001E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (122, '40936668E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (123, '1128474161E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (124, '80883010E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (125, '80170660E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (126, '1075284985E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (127, '83042295E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (128, '1152210959E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (129, '1022380991E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (130, '1115069820E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (131, '331789E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (132, '1151954545E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (133, '1019011177E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (134, '1047451443E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (135, '1032467291E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (136, '1140847297E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (137, '30405867E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (138, '1095826986E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (139, '1026255124E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (140, '1075292422E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (141, '1056709240E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (142, '53103915E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (143, '1098725794E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (144, '1075292404E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (145, '1098755426E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (146, '1110502030E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (147, '30400528E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (148, '1026292916E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (149, '52969518E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (150, '1075293846E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (151, '1049619319E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (152, '1091660311E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (153, '1010167959E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (154, '1098739269E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (155, '63527981E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (156, '1085247861E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (157, '91520047E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (158, '10297751E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (159, '1026267749E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (160, '1098782789E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (161, '13740129E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (162, '1012387614E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (163, '37514608E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (164, '1075286382E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (165, '1098697791E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (166, '13720871E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (167, '1023961699E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (168, '1098733967E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (169, '1072699593E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (170, '1007555164E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (171, '63540751E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (172, '1143327261E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (173, '80777836E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (174, '1018455383E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (175, '1098745210E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (176, '1016597E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (177, '1013633604E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (178, '1003934174E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (179, '91524899E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (180, '1045706790E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (181, '1040746072E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (182, '1014262113E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (183, '37546080E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (184, '1075212439E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (185, '1098726424E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (186, '1087047704E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (187, '1098663949E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (188, '1032398017E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (189, '506169E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (190, '80074517E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (191, '1013629348E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (192, '91514446E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (193, '1053792535E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (194, '79686130E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (195, '1098605467E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (196, '1098795831E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (197, '1098610954E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (198, '1101693549E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (199, '1098692205E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (200, '1065599609E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (201, '1098758681E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (202, '1098706838E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (203, '91527985E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (204, '1098681773E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (205, '1091668362E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (206, '51781946E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (207, '1100961505E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (208, '74085101E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (209, '1101692935E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (210, '13959717E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (211, '52455261E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (212, '1121941649E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (213, 'Funciones_Profe_Proyecto_Ii', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (214, 'A_Company_Man_D1', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (215, 'A_Company_Man_D2', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (216, 'A_Company_Man_D3', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (217, 'Supervisor_Operaciones_Tipo_1', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (218, 'Supervisor_Operaciones_Tipo_2', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (219, 'Supervisor_Operaciones_Tipo_3', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (220, 'Supervisor_Operaciones_Tipo_4', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (221, 'Supervisor_Operaciones_Tipo_5', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (222, 'Supervisor_Operaciones_Tipo_6', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (223, 'Soporte_Operativo_Tipo_1', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (224, 'Soporte_Operativo_Tipo_2', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (225, 'Soporte_Operativo_Tipo_3A', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (226, 'Soporte_Operativo_Tipo_3B', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (227, 'Sop_Ope_Tipo_3A_Conductores', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (228, 'Soporte_Operativo_Tipo_4A', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (229, 'Soporte_Operativo_Tipo_4B', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (230, 'Sop_Ope_Tipo_4A_Conductores', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (231, 'Soporte_Operativo_Tipo_5A', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (232, 'Soporte_Operativo_Tipo_5B', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (233, 'Sop_Ope_Tipo_5A_Conductores', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (234, 'Pro Especialista Helman', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (235, 'Funciones_Analista_Contable', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (236, 'Profesional Senior Juan -3', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (237, 'Profesional Senior Edisson', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (238, 'Profesional Junior Edgar', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (239, 'Profesional Basico Denissary', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (240, 'Profesional Senior Caroly', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (241, 'Profesional Senior Manuel', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (242, 'Profesional Senior Eduar', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (243, 'Profesional Senior  Willliam', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (244, 'Profesional Senior Carlos', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (245, 'Profesional Junior Juan -3', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (246, 'Profesional Junior  Dilan', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (247, 'Profesional Basico Laura', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (248, 'Profesional Basico  Sonia', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (249, 'Profesional Especialista Carlos', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (250, 'Profesional Senior Jose', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (251, 'Profesional Senior Victor', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (252, 'Profesional Senior Gloria', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (253, 'Profesional Junior Juan -2', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (254, 'Profesional Junior Jhan', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (255, 'Profesional Junior Gerardo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (256, 'Profesional Junior Angie', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (257, 'Profesional Junior Christian', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (258, 'Profesional Junior Xiomara', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (259, 'Profesional Junior Gustavo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (260, 'Profesional Senior Maria M', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (261, 'Profesional Junior Carlos -3', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (262, 'Profesional Junior Alberto', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (263, '1032446831E', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (264, 'Profesional Junior Jean', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (265, 'Profesional Junior Yohan', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (266, 'Profesional Junior Jose A', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (267, 'Profesional Especialista Mario', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (268, 'Profesional Especialista Jorge', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (269, 'Profesional Especialista Gladys', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (270, 'Profesional Especialista Oscar', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (271, 'Profe Especialista Alexander', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (272, 'Profesional Senior Angelica', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (273, 'Profesional Senior Gabriel', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (274, 'Profesional Senior Mariann', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (275, 'Profesional Senior Diana', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (276, 'Profesional Senior Juan', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (277, 'Profesional Especialista Ruben', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (278, 'Profesional Senior Gilberto', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (279, 'Profesional Senior Leidy', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (280, 'Profesional Senior Jorge', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (281, 'Profesional Junior William', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (282, 'Profesional Senior Max', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (283, 'Profesional Junior Andres', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (284, 'Profesional Junior Lady', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (285, 'Profesional Junior Ana', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (286, 'Profesional Junior Luisa', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (287, 'Profesional Junior Julian', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (288, 'Profesional Junior Alexandra', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (289, 'Profesional Junior Maylin', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (290, 'Profesional Junior Karen', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (291, 'Profesional Junior Carlos -2', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (292, 'Profesional Senior Camila', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (293, 'Profesional Senior Ruben G', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (294, 'Profesional Senior Oscar', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (295, 'Profesional Senior Ivan', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (296, 'Profesional Senior Daniel', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (297, 'Profesional Junior Ruben Ortiz', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (298, 'Profesional Junior Juan', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (299, 'Profesional Junior Jose', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (300, 'Profesional Basico Camilo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (301, 'Profesional Basico Fernanda', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (302, 'Profesional Basico Nicolas', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (303, 'Profesional Senior Eduardo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (304, 'Profesional Senior Alejandro', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (305, 'Profesional Senior Carolina', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (306, 'Profesional Basico  Daniela', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (307, 'Pro Especialista Adriana', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (308, 'Funciones_Soporte_It', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (309, 'Profesional Senior Mario', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (310, 'Profesional Junior Liz', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (311, 'Prof_ Soporte Op_Campo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (312, 'Funciones_Sop_Hseqcm', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (313, 'Funciones_Asis_Admon_Cm', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (314, 'Funciones_Gerente_General', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (315, 'Funciones_Subgerente', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (316, 'Funciones_Gerente_Administratvo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (317, 'Funciones_Director_Proyectos', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (318, 'Funciones_Coordinador_Hseq', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (319, 'Funciones_Coordinador_Contable', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (320, 'Funciones_Coordinador_Gh', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (321, 'Funciones_Profesional_Hseq', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (322, 'Funciones_Prof_Proye_Mb', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (323, 'Funciones_Contador_Junior', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (324, 'Funciones_Contador_Junior_Al', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (325, 'Funciones_Soporte_Hseq_Adm', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (326, 'Funciones_Asistente_Gh', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (327, 'Funciones_Analista_Nomina', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (328, 'Funciones_Asistente_Adm_Dis', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (329, 'Funciones_Asistente_Adm_Dis_Ii', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (330, 'Funciones_Asistente_Adm', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (331, 'Funciones_Asistente_Logistica', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (332, 'Funciones_Servicios_Generales', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (333, 'Funciones_Prof_Proye_Alta', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (334, 'Funciones_Asistente_Licitacione', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (335, 'Profesional Admon_Gh_Cm', '', '', '');
COMMIT;
