START TRANSACTION;
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (110, 'Junior Paola Gomez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (111, 'Cargo Sin Nombre', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (112, 'Especialista Alexandra Isabel Mesa Cardenas', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (113, 'Senior Diana Paola Solano Sua', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (114, 'Especialista Edna Miled Nino Orozco', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (115, 'Junior Laura Maria Hernandez Riveros', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (116, 'Senior Zenaida  Valle Marcano De Villarroel', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (117, 'Senior Cindy Natalia Isaza Toro', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (118, 'Junior Emeli Johana Yacelga Chitan', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (119, 'Junior Esperanza De Jesus Cotes Leon', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (120, 'Senior Leidy Laura Alvarez Berrio', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (121, 'Senior Oveimar Santamaria Torres', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (122, 'Especialista Ruben Hernan Castro Garcia', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (123, 'Junior Sebastian Llanos Gallo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (124, 'Senior William Cabrera Castro', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (125, 'Basico Carlos Alberto Olano Martinez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (126, 'Junior Diego Castillo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (127, 'Senior Gabriel Velez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (128, 'Especialista Gladys Tabares', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (129, 'Senior Juan M Cordoba', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (130, 'Senior Leidy Bello', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (131, 'Basico Carlos Rafael Olmos Carval', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (132, 'Basico Christian Mauricio Pardo Carranza', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (133, 'Senior David Alejandro Garcia', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (134, 'Junior Diana Marcela Caceres Salinas', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (135, 'Junior Lizeth Dayana Bautista Rico', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (136, 'Junior Maria Alejandra Mojica Arciniegas', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (137, 'Junior Olmer Andres Morales Mora', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (138, 'Senior Ivan Dario Mozos Moreno', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (139, 'Senior Monica  Pilar Martinez Vera', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (140, 'Junior Jose Gabriel Nassar Diaz', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (141, 'Junior Francisco Jose Amado Iriarte', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (142, 'Junior Jaime Martinez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (143, 'Senior Diana Maria Hernandez Castro', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (144, 'Blanca Offir Hurtado Lopera', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (145, 'Basico Camilo Andres Santana Otalora', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (146, 'Senior Carolina Leon Vanegas', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (147, 'Junior Daniela Molina Landinez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (148, 'Senior Diego Armando Vanegas Araque', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (149, 'Senior Eduar Ernesto Perez Rojas', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (150, 'Senior Franklin Alejandro Botero Rivera', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (151, 'Junior Gustavo Adolfo Moreno Beltran', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (152, 'Senior Ina Yadith Serrano Lastre', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (153, 'Senior Ivan Dario Moncayo Riascos', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (154, 'Junior Jesus David Arenas Navarro', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (155, 'Senior Jose Manuel Garcia Orozco', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (156, 'Junior Juan David Aristizabal Marulanda', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (157, 'Junior Juan Sebastian Avila Parra', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (158, 'Senior Julio Cesar Figueroa Vega', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (159, 'Junior Leonardo Santos Mateus Baez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (160, 'Senior Lucia Maria Acero Lizcano', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (161, 'Junior Maria Alejandra Cabrera Garcia', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (162, 'Senior Maria Alejandra Joya Rincon', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (163, 'Especialista Mario Augusto Moreno Castellanos', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (164, 'Basico Nicolas Avendano Vasquez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (165, 'Senior Oscar Fabian Suarez Suarez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (166, 'Junior Ruben Dario Ortiz Murcia', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (167, 'Basico Sergio Fernando Poveda Salazar', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (168, 'Senior Adriana Patricia Duenes Garces', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (169, 'Senior Donaldo Eduardo Ramos Vanegas', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (170, 'Junior Jesus Ernesto Coqueco Vargas', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (171, 'Senior Ruben Alberto Gonzalez Lopez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (172, 'Junior Estefany Lizeth Velandia Jaimes', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (173, 'Senior Jean Pablo Cedeno Orfila', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (174, 'Junior Gustavo Andres Bautista Velandia', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (175, 'Junior Jhon Abelardo Cuesta Asprilla', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (176, 'Junior Jose Andres Anaya Mancipe', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (177, 'Junior Jose Carlos Garcia Rueda', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (178, 'Junior Kelly Lorena Diez Hernandez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (179, 'Junior Maria Angelica Prada Fonseca', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (180, 'Senior Maria Himelda Murillo Lopez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (181, 'Senior Mariann Lissette Mahecha Laverde', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (182, 'Junior Emmanuel Robles Albarracin', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (183, 'Junior Yuber Rodriguez Arturo', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (184, 'Junior Hernan Albeyro Fula Bohorquez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (185, 'Senior Claudia Caroprese Garcia', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (186, 'Especialista Cristian Penafort Gavria', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (187, 'Junior Christian Camilo Rivera Sanchez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (188, 'Senior German Dario Orejarena Escobar', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (189, 'Junior Leidi Marcela Quintero Giraldo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (190, 'Senior Ricardo Gaviria Garcia', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (191, 'Junior Max Gomez Gualdron', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (192, 'Junior Sonia Alejandra Quintero', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (193, 'Junior Jorge Coronado', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (194, 'Junior Cersar Garnica', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (195, 'Junior Cesar Rodriguez', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (196, 'Junior Julian Hernandez Pinto', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (197, 'Junior Jhon Rojas', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (198, 'Junior Jhon Carreno', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (199, 'Junior Jesus Pacheco', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (200, 'Senior Gloria Vidal', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (201, 'Junior Geisson Zafra', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (202, 'Senior Edwin Hernandez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (203, 'Junior Diego Pinto', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (204, 'Senior Galenao', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (205, 'Junior Ana Maria Castellanos Barreto', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (206, 'Junior Alejandro Lopez', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (207, 'Especialista Helman', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (208, 'Senior Juan', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (209, 'Basico Edgar', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (210, 'Basico Denissary', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (211, 'Senior Caroly', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (212, 'Senior Manuel', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (213, 'Senior Eduar', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (214, 'Senior Willliam', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (215, 'Senior Carlos', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (216, 'Junior Juan', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (217, 'Junior Dilan', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (218, 'Basico Laura', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (219, 'Basico Sonia', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (220, 'Especialista Carlos', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (221, 'Senior Jose', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (222, 'Senior Victor', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Junior Juan';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (223, 'Junior Jhan', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (224, 'Junior Gerardo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (225, 'Junior Angie', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (226, 'Junior Xiomara', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (227, 'Junior Gustavo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (228, 'Senior Maria', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (229, 'Junior Carlos', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (230, 'Junior Alberto', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (231, 'Junior Maria Prada', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (232, 'Junior Jean', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (233, 'Junior Yohan', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (234, 'Junior Jose', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (235, 'Especialista Mario', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (236, 'Especialista Jorge', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (237, 'Especialista Gladys', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (238, 'Especialista Oscar', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (239, 'Especialista Alexander', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (240, 'Senior Angelica', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (241, 'Senior Gabriel', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (242, 'Senior Mariann', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (243, 'Senior Diana', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Senior Juan';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (244, 'Especialista Ruben', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (245, 'Senior Gilberto', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (246, 'Senior Leidy', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (247, 'Senior Jorge', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (248, 'Junior William', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (249, 'Senior Max', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (250, 'Junior Andres', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (251, 'Junior Lady', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (252, 'Junior Ana', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (253, 'Junior Luisa', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (254, 'Junior Julian', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (255, 'Junior Alexandra', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (256, 'Junior Karen', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Junior Carlos';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (257, 'Senior Camila', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (258, 'Senior Ruben Gonzalez', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (259, 'Senior Oscar', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (260, 'Senior Ivan', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (261, 'Senior Daniel', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (262, 'Junior Ruben Ortiz', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Junior Juan';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Junior Jose';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (263, 'Basico Camilo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (264, 'Basico Fernanda', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (265, 'Basico Nicolas', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (266, 'Senior Eduardo', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (267, 'Senior Alejandro', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (268, 'Senior Carolina', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (269, 'Basico Daniela', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (270, 'Especialista Adriana', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (271, 'Senior Mario', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (272, 'Junior Liz', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Junior Gustavo';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (273, 'Junior Alvaro', '', '', '');
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (274, 'Basico Emmanuel', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (275, 'Senior Blanca', '', '', '');
UPDATE cargo SET descripcion_cargo='', objetivo_cargo='', proceso_gestion='' WHERE nombre_cargo='Cargo Sin Nombre';
INSERT INTO cargo (id_cargo, nombre_cargo, descripcion_cargo, objetivo_cargo, proceso_gestion) VALUES (276, 'Junior Maria', '', '', '');
COMMIT;
